# Generated by Django 3.2.16 on 2023-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
